---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olof.sh
  labels:
    app: homepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: olof.sh
        image: ghcr.io/olofthesnowman/olof.sh:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
spec:
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "olof.sh"
    secretName: olof-sh-server-tls
  rules:
  - host: olof.sh
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 80